daos-stack/cart

src/cart/crt_context.c
src/cart/crt_rpc.c

Prevent double untrack from happening in some situations when rpc
timeout happens close in time to failure to forward rpc.
Signed-off-by: Alex Oganezov <alexander.a.oganezov@intel.com>

CART-89 fix: Prevent double untrack from happening

---

src/utest/utest_cmocka.c
src/utest/utest_cmocka.h

Change the type of the pmix event register function to use a void *
so it works with both the old and new PMIx versions.
Note this doesn't update PMIx itself as there are other issues
preventing that currently, however this does mean the unit tests
now work with either version to make the update easier.
Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

CART-89 pmix: Update unit tests to work with later PMIx versions.

---

src/cart/crt_context.c
src/cart/crt_rpc.h

crt_context_req_track used crp_in_binheap indicator to prevent
double untrack, but that indicator could be cleared by the lower
level rpc untrack code.
Instead new crp_ctx_tracked indicator added to crt_rpc_priv
structure for the double untrack prevention purpose.

CART-593 bugfix: hang/assertion at exit when destroying context

---

src/cart/crt_rpc.c

Cleaned up uri lookup logic, along with freed pointer previously
being returned during endpoint address lookup.
Singed-off-by: Alex Oganezov <alexander.a.oganezov@intel.com>

CART-89 cleanup: uri lookup cleanup

---

SConstruct
src/SConscript
src/include/gurt/atomic.h
src/utest/test_gurt.c

Add a header that abstracts compiler specific atomic intrinisics.

CART-286 gurt: Add atomics header to gurt

---

src/cart/crt_register.c
src/include/cart/api.h
src/test/test_proto_client.c
src/test/test_proto_common.h

- crt_proto_register() will now return -DER_EXIST if base_opc:version
tuple is already registered.
- crt_proto_unregister(base_opc, ver) API added to allow
unregistration of existing base_opc:version tuple.
- test_proto_client test modified to check for new behavior of
crt_proto_register and crt_proto_unregister.

CART-595 proto: Prevent double registration

---

src/cart/crt_group.c
src/cart/crt_init.c
src/cart/crt_internal_types.h
src/cart/crt_pmix.c
src/cart/crt_pmix.h
src/cart/crt_swim.c
src/include/cart/api.h

We have internal API for events related to rank state. This API is used
to provide rank eviction mechanism. With new bootstrapping approach we
should provide ability to subscribe on those events outside of CaRT to
manage groups members outside. So, move this API to public.
Move initialization of PMIx from crt_register_event_cb() into
crt_plugin_init().

CART-594 group: Provide public API for events

---

src/gurt/fault_inject.c
src/include/gurt/fault_inject.h

Update fa_num_faults during fault_attr_set,
so DAOS can reset the fa_num_faults to 0.
Signed-off-by: Wang Di <di.wang@intel.com>

CART-600 fault: update fa_num_faults

---

src/cart/crt_context.c

avoid calling HG_Cancel() on an RPC after success-and-failure HG_Forward() call.
Sometimes HG_Forward() returns success but actually failed to send
inside. In that case mercury already called NA_Cancel() on that RPC and
posted completion callback. Calling HG_Cancel() a second time will lose
the completion callback somehow.

CART-89 timeout: avoid RPC double cancel

---

src/cart/crt_context.c
src/cart/crt_init.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/include/cart/types.h
src/test/SConscript
src/test/test_ep_cred_client.c
src/test/test_ep_cred_common.h
src/test/test_ep_cred_server.c
test/cart_test_ep_credits.py
test/cart_test_ep_credits.yml
test/test_list.yml
utils/run_test.sh

- Bug: during untrack, wrong rpc_priv's field was being set
- Modified queue process logic to use temp variable
- Added new fields to crt_init_options_t:
* cio_use_credits
* cio_ep_credits
These two options allow setting of EP credits value similar to
CRT_CTX_EP_CREDITS environment variable.
- Added new 'cart_test_ep_credits' test with new server/client that
utilize new crt_init_options_t fields.
Test goes through few different ep_credits settings and sends
100 rpcs for each value.
Signed-off-by: Alex Oganezov <alexander.a.oganezov@intel.com>

CART-598 bugfix: client hangs with multiple RPCs in flight

---

src/gurt/fault_inject.c

Fix a bug in fault injection. The attribute pointer that controls FI in
memory allocations was not initialized.
Ashley found the bug.

CART-89 gurt: fix bug in fault injection

---

src/test/test_ep_cred_client.c

Group was being destroyed before all accesses to it were stopped

CART-609 bugfix: segfault in ep_credits test

---

src/gurt/hash.c
src/include/gurt/hash.h

Gurt should only support generic bits in the hash implementation,
and therefore all DAOS custom bits should be removed for handle types.
Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

DAOS-1801 gurt: Move DAOS Handle types from GURT to DAOS

---

src/cart/crt_context.c
src/cart/crt_internal_types.h
src/cart/crt_register.c
src/cart/crt_swim.c
src/include/cart/types.h
src/include/gurt/common.h
src/test/test_ep_cred_client.c
src/test/test_ep_cred_common.h
test/cart_test_ep_credits.py

- CRT_RPC_FEAT_QUEUE_FRONT rpc flag added. When set forces rpc to
be put into the front of the queue instead of being added to the
tail of it.
- SWIM rpcs now set new CRT_RPC_FEAT_QUEUE_FRONT flag
- ep_credits test case modified to test new queueing feature

CART-617 rpc: Add option to queue rpcs into front of the queue

---

src/include/gurt/common.h
src/utest/test_gurt.c

D_REALLOC_ARRAY_COMMON macro had a bug in which 'cnt' can be expanded
incorrectly due to missing ()'s.

CART-89 bug: Fix in realloc array macro

---

src/cart/crt_context.c
src/cart/crt_hg.c
src/cart/crt_hg_proc.c
src/cart/crt_internal.h
src/cart/crt_internal_types.h
src/cart/crt_rpc.c
src/cart/crt_rpc.h

- new cch_xid field added to rpc header
- global xid is incremented on each rpc creation
- opc and xid are now printed as part of RPC_TRACE/RPC_ERROR macros

CART-644 rpc: New transfer id field in rpc header

---

src/cart/crt_init.c

- -DER_NONEXIST error is now returned if provider requested via
CRT_PHY_ADDR_STR is not found.

CART-665 init: Return error if provider is not found

---

src/gurt/debug.c
src/include/gurt/dlog.h

Add a function to set default DD_MASK. Currently the only way to set
DD_MASK is via the shell variable.

CART-629 log: add function to set DD_MASK

---

src/cart/crt_group.c
src/test/SConscript
src/test/no_pmix_multi_ctx.c
test/cart_test_no_pmix_multi_ctx.py
test/cart_test_no_pmix_multi_ctx.yml
test/test_list.yml
utils/run_test.sh

- URI table was previously incorrectly destroyed during context
invalidation. URI table should only be destroyed during group
destruction.
- no_pmix_multi_ctx test added

CART-644 bug: uri entry destruction asserts

---

src/gurt/debug.c

add an implicit call to d_log_sync_mask() in d_log_init()
Signed-off-by: Yulu Jia <yulu.jia@intel.com>

CART-646 gurt: call d_log_sync_mask in d_log_init

---

src/cart/crt_group.c
src/cart/crt_rpc.c
src/crt_launch/SConscript
src/crt_launch/crt_launch.c
src/include/cart/api.h
src/test/SConscript
src/test/no_pmix_launcher_client.c
src/test/no_pmix_launcher_common.h
src/test/no_pmix_launcher_server.c
src/test/tests_common.h
test/cart_test_no_pmix_launcher.py
test/cart_test_no_pmix_launcher.yml
test/test_list.yml
utils/run_test.sh

- crt_launch utility added to generate environment for running during
NO_PMIX mode of operation. Launcher generates group configuration
file and executes passed application.
Launcher will specify CRT_L_RANK for self-rank for servers to use
and CRT_L_GRP_CFG for path to group configuration file.
- New no_pmix_launcher test added consisting of client and multiple
servers utilizing new crt_launch utility.
- New APIs added:
crt_group_view_create()
crt_group_view_destroy()
crt_group_psr_set()
These APIs are used by clients during NO_PMIX mode of operation to
create group. Once created server nodes can be added dynamically
to that group using existing crt_group_node_add() API.
The behavior of these APIs is similar to crt_group_attach(), except
groups can be populated dynamically without …

CART-603 launcher: New crt_launch utility added

---

Jenkinsfile
SConstruct
multi-node-test.sh
test/launch.py

CaRT tests are migrated to run with Avocado.
Removing test_runner from CI.

CART-701 Remove test_runner from CI

---

Jenkinsfile

This is a fix for any Jenkins build that does not kick off tests.

CART-703 Fix Jenkinsfile that attempts to move non-existent folders

---

src/test/tests_common.h

Provide ample buffer space so that *printf() functions don't cause errors like
this on newer GCC:
= = = =
error: '%d' directive writing between 1 and 11 bytes into a region of
size between 0 and 254 [-Werror=format-overflow=]
= = = =
Signed-off-by: Yulu Jia <yulu.jia@intel.com>

CART-702 test: fix format overflow warning

---

src/crt_launch/crt_launch.c

argv in execve() should contain the executable name as the first
string. By default getopt and getopt_long starts parsing at the
second string.

CART-89 launcher: fix argv in execve

---

test/barrier/cart_barrier_five_node.py
test/barrier/cart_barrier_one_node.py
test/barrier/cart_barrier_two_node.py
test/corpc/cart_corpc_five_node.py
test/corpc/cart_corpc_one_node.py
test/corpc/cart_corpc_two_node.py
test/ctl/cart_ctl_five_node.py
test/ctl/cart_ctl_one_node.py
test/group_tiers/cart_group_tiers_three_node.py
test/iv/cart_iv_one_node.py
test/iv/cart_iv_two_node.py
test/launch.py
test/no_pmix/cart_nopmix_multictx_one_node.py
test/no_pmix/cart_nopmix_one_node.py
test/nopmix_launcher/cart_nopmix_launcher_one_node.py
test/rpc/cart_rpc_one_node.py
test/rpc/cart_rpc_two_node.py
test/selftest/cart_selftest_two_node.py
test/singleton/cart_singleton_one_node.py
test/singleton/cart_singleton_two_node.py
test/util/cart_utils.py

When avocado runs, the server/client cmd prints are directed
to stdout, which is logged in avocado's path.
This patch enables avocado progress logging.
This will make reproducing tests easier by using the underlying
orterun cmd without searching the avocado logs.

CART-705 Enable runtime logging of server/client commands

---

src/cart/crt_group.c
src/cart/crt_group.h
src/cart/crt_pmix.c
src/crt_launch/crt_launch.c
src/test/iv_client.c
src/test/iv_server.c
src/test/tests_common.h
test/iv/cart_iv_one_node.yaml
test/iv/cart_iv_two_node.yaml

- iv_client/iv_server converted to no-pmix mode of operation
- iv_server is now launched using crt_launch tool
- crt_launch fixed to stop processing arguments after 'cmd to exec'
is parsed out.
- crt_group_attach() changed for non-pmix mode to create group view
and populate all uris in internal cache
- crt_group_config_save() fixed for non-pmix mode to not rely on
pmix lookups.

CART-706 test: Convert IV tests to no-pmix mode

---

src/swim/swim.c

Fix unlocking context before return from function.

CART-730 swim: unlock SWIM context before DEAD

---

src/cart/crt_group.c
src/cart/crt_rpc.c

Checking return code and returning if not 0 in
crt_req_uri_lookup_by_rpc_cb and
crt_uri_lookup_forward_cb
This is to avoid crt_req_fill_tgt_uri asserting NULL uri.

CART-737 Adding return code checks before crt_req_fill_tgt_uri

---

Makefile
cart.spec

... in RPM builds.
For forensic purposes, it would be useful to have the git hash of the
CaRT build in the Release of the RPM.

CART-89: build: Add a git hash to Release string

---

SConstruct
cart.spec
debian/changelog
src/cart/crt_group.c
src/include/cart/api.h
src/include/cart/types.h
src/test/no_pmix_group_test.c

New APIs:
- crt_group_primary_modify
- crt_group_secondary_modify
New APIs allow atomic modification of primary/secondary group
membership based on the operation type specified. Currently supported
operations are: Replace, Add, Remove.
New Type:
- crt_group_mod_op_t
no_pmix_group_test updated to include test cases of newly added APIs.

CART-713: Add new group atomic modification apis

---

src/cart/crt_context.c
src/include/cart/api.h

Fix a bug in crt_context_flush(). When the timeout value is not 0,
crt_context_flush() returns right away instead of keep progressing the
context for timeout amout of time.

CART-89 cart: fix bug in crt_context_flush()

---

utils/docker/Dockerfile-debbuild.ubuntu.18.04
utils/docker/Dockerfile-debbuild.ubuntu.18.10
utils/docker/Dockerfile.leap.15

- update the mercury deb version to libmercury1_1.0.1-9 to match the
version in the mercury deb build repo
- fix dockerfile for leap 15: should be requesting "leap:15" not
"leap15.0"

CART-751 build: update dockerfiles

---

src/cart/crt_hg.c
src/cart/crt_init.c

If OFI_PORT is not specified, let mercury pick tcp ports. Currently cart
finds a free port then pass it to mercury. When many processes are
running on the same node, processes may use the same port, this will
cause problems.

CART-752 cart: let mercury pick its own ports

---

src/cart/crt_hg.c
src/cart/crt_internal.h
src/cart/crt_register.c
src/cart/crt_rpc.c
src/test/test_corpc_version.c

fix intermittent failure of the test_corpc_version test.
After using the HG_Cancel() workaround in mercury, the reported error in
the ticket doesn't show up any more. Instead the test hangs from time to
time.
The reason was 1) during shutdown the lm module is interfering with the
corpc version mismatch test. 2) when runing many (tried 32 and 64)
processes on a single node, sometimes two processes pick the same port
number. If one process finishes early and exits, the other process can't
receive the shtudown RPC anymore. This causes a hang.
The reason 2 above is still not fixed.

CART-592 test: fix test_corpc_version failure

---

src/test/SConscript
src/test/iv_client.c
src/test/iv_common.h
src/test/iv_server.c
src/test/no_pmix_group_test.c
src/test/no_pmix_launcher_client.c
src/test/no_pmix_launcher_server.c
src/test/tests_common.h

A new function "wait_for_ranks" in tests_common that can be used in tests
to ensure server readiness before starting main test. The function uses
internal RPC to ping server until all rank:tag are ready.

CART-715 Implement common synchronization function to ensure server readiness

---

src/cart/crt_context.c
src/cart/crt_hg.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h

1) If the RPC is inflight then depend on HG_Cancel() that it will
trigger the RPC's completion.
2) For other cases, trigger the RPC's completion only once.
The motivation is to fix a timeout caused hang for DAOS-2469, in that
case the URI_LOOKUP timedout then the original RPC hang, it should due
to in crt_req_timeout_hdlr() it calls crt_req_abort() but that did not
trigger RPC completion.

DAOS-2469 rpc: refine crt_req_abort handling

---

src/include/gurt/debug.h
src/utest/test_gurt.c
src/utest/utest_hlc.c

In order to catch internal assertions in cmocka unit tests,
we need to register mock_assert.   This doesn't work when
the assertion is D_ASSERTF because that code path ignores
the alternate assert function setting.
Also, register mock_assert in unit tests so internal assertions
are properly caught and reported by cmocka.  This doesn't
work for test_linkage.cpp but that is a separate issue that
doesn't need to be solved for this ticket

DAOS-3109 test: D_ASSERTF ignores alternate assert registration

---

src/cart/crt_corpc.c
src/include/cart/api.h
src/test/test_corpc_prefwd.c

New optional co_post_reply callback to be executed after CORPC
response is sent to the parent (post co_aggregate).
Can be used for cleaning data allocated in co_aggregate callback.

CART-763 corpc: New optional co_post_reply callback

---

src/cart/crt_corpc.c
src/cart/crt_tree.c
src/test/no_pmix_group_test.c
test/corpc/cart_corpc_five_node.yaml
test/corpc/cart_corpc_one_node.yaml
test/corpc/cart_corpc_two_node.yaml

- CORPC tree was not being generated correctly for secondary groups
when running in PMIX enabled mode.
- Re-enabled corpc version test that hit issues previously due to this
bug

CART-759 corpc: Incorrect tree generation for secondary groups

---

src/cart/crt_hlc.c
src/include/cart/api.h

To allow user can retrieve second timestamp of hlc.

DAOS-2444 hlc: add crt_hlc2sec

---

SConstruct
cart.spec
debian/changelog
src/cart/crt_hg.c
src/cart/crt_hg.h
src/cart/crt_hg_proc.c
src/cart/crt_internal_types.h
src/cart/crt_register.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/include/cart/api.h
src/include/cart/types.h
src/test/test_swim_net.c
src/utest/test_linkage.cpp
utils/test_cart_lib.sh

* remove old unused code (simplify serialization pipeline)
* add new RAW member in macro to copy whole struct
* make few functions static
* copy whole struct insted of coping by each member

CRT-760 rpc: optimization RPC serialization pipeline

---

src/test/test_corpc_exclusive.c
src/test/test_corpc_prefwd.c
src/test/tests_common.h

- test_corpc_exclusive and prefwd changed to use tc_drain_queue()
in order to drain queue before exiting, instead of doing a loop of
context progress
- minor cleanup in naming of drain_queue and regular prints changed
to ERROR/DEBUG macros.

CART-770 test: corpc_exclusive hangs over verbs (with lm disabled)

---

src/cart/crt_context.c
src/cart/crt_hg.c
src/cart/crt_internal.h
test/util/cart_logtest.py

- fix an issue in the RPC_TRACE macro to make it work with arguments
like &rpc_priv_temp
- change the tracing message format so that following the trace of an
RPC in the log file is easier. Now the RPC trace message format is:
[opc=0xa010001 xid=0x15bf rank:tag=3:7]
where 0x15bf is the unique sequence ID, 3:7 is the
target_rank:target_tag.

CART-89 logging: add more logging

---

src/cart/crt_group.c

Fixed a bug in crt_group_config_save() for non-pmix case, where
incorrect ranks were used for uri retrieval.

CART-89 fix: Fix bug in crt_group_config_save()

---

src/cart/crt_ctl.c

Number of contexts returned was not being protected by the lock, which could result in a mismatch between num_ctx returned and the list of context addresses

CART-89 fix: Protect returned number of contexts

---

SConstruct
cart.spec
debian/changelog
src/cart/crt_hg.c
src/cart/crt_hg_proc.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/include/cart/api.h
src/test/no_pmix_group_test.c
src/test/no_pmix_launcher_common.h

New APIs:
- crt_req_dst_rank_get()
- crt_req_dst_tag_get()
- crt_req_src_rank_get()
Modified no_pmix_group_test and no_pmix_launcher test to use
new APIs.
Fixed no_pmix_group_test's DBG_PRINT

CART-790 rpc: Add new APIs to get src/dst rank

---

src/cart/crt_init.c
src/include/gurt/common.h
src/test/iv_server.c
test/iv/cart_iv_one_node.yaml
test/iv/cart_iv_two_node.yaml

- iv_server test fixed to wait for ranks before doing namespace attach
- only rank0 now saves iv group info
- yaml files changed to launch 5 servers; server/clients set to have 2
contexts via CRT_CTX_NUM
- unused -x CRT_ALLOW_SINGLETON=1 removed
- D_REALLOC_COMMON macro modified to print sizes and counts as size_t/zu.
This also fixes CART-793.
- Debug print added to print server bit at startup

CART-792 iv: Fix iv_server test

---

src/include/gurt/debug.h

The gurt log should reflect that an assertion triggered.

CART-89 debug: D_ASSERT should print to log before calling assert

---

src/cart/crt_iv.c

crt_hdlr_iv_sync leaks one ivns_internal reference on the common path.
On the error path, it drops a nonexistent reference by mistake.
Signed-off-by: Li Wei <wei.g.li@intel.com>

CART-797 iv: Fix crt_hdlr_iv_sync NS ref leaks

---

src/ctl/cart_ctl.c

Cart ctl is not using path set by option --cfg_path.
This is a fix in ctl to call crt_group_config_path_set()

CART-799 Fix Cart ctl to lookup server cfg file in the path set by cfg_path

---

utils/rpms/cart.spec
utils/rpms/debian/control

mercury-1.0.1-20 was causing IOR and mdtest to fail in DAOS testing.

CART-89: Pin mercury to < 1.0.1-20 due to incompatiblity

---

utils/rpms/cart.spec

From cart-devel since it breaks ior building because ior ends up
building with ompi instead of mpich.
The right solution is to build an environment-module-ized ompi.

CART-89 build: Remove R: ompi-devel

---

SConstruct
src/gurt/errno.c
src/include/gurt/errno.h
src/utest/test_gurt.c
src/utest/test_gurt_v1.c
utils/rpms/cart.spec
utils/rpms/debian/changelog

Create an API in gurt to register error strings with gurt.
Remove DAOS error codes under new D_ERRNO_V2 #define

DAOS-3677 errno: Move DAOS error codes back to DAOS

---

src/cart/crt_group.c

Off by 1 error when filling group id from file. Group name should
account for trailing '\0'

CART-89 fix: Off by 1 error

---

src/cart/crt_iv.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/include/cart/iv.h

Add a new IV callback, ivo_pre_sync, which will be called before
forwarding IV_SYNC requests to children (if any), in order to update a
special IV whose value defines the IV NS's group membership.
Signed-off-by: Li Wei <wei.g.li@intel.com>

DAOS-2822 iv: Add ivo_pre_sync

---

src/cart/crt_corpc.c

If rank 0, whose local primary group comprising {0, 1, 2}, sends a
CRT_RPC_FLAG_EXCLUSIVE CoRPC to {0, 1, 2}, and if rank 1 receives the
request but has a stale local primary group comprising only {1}, then
rank 1 will return -DER_OOG in crt_corpc_info_init. The user does not
immediately know whether the -DER_OOG is due to his {0, 1, 2} exclusive
rank list being incorrect or one of the remote ranks possessing a
mismatching group membership. Moreover, accessing the group membership
in crt_corpc_info_init in order to perform the -DER_OOG check happens
before the CoRPC's pre_forward callback gets a chance to run, violating
the pre_forward semantics. This patch removes the -DER_OOG check in
crt_corpc_info_init and defers it to crt_get_filtered_grp_rank_list,
called after performing the group …

CART-818 corpc: Fix -DER_OOGs from crt_corpc_info_init

---

utils/rpms/Makefile

Ditto for scons_local tarball.
We need to do this because we don't have any reasonable source of
dependencies to list for the tarballs.

CART-89 build: Always build the cart tarball

---

SConstruct
src/cart/crt_corpc.c
src/cart/crt_group.c
src/cart/crt_tree.c
src/include/cart/api.h
src/test/SConscript
src/test/no_pmix_group_version.c
test/corpc/cart_corpc_five_node.yaml
test/corpc/cart_corpc_one_node.yaml
test/corpc/cart_corpc_two_node.yaml
test/group_test/group_test.py
test/group_test/group_test.yaml
utils/rpms/cart.spec
utils/rpms/debian/changelog

- CORPCs are now passed proper associated group versions instead of
the primary groups versions.

CART-819 grp: Group versioning over secondary groups

---

SConstruct
src/cart/crt_corpc.c
src/cart/crt_tree.c
src/include/gurt/errno.h
src/test/no_pmix_group_version.c
src/test/test_corpc_version.c
utils/rpms/cart.spec
utils/rpms/debian/changelog

- New DER_GRPVER error code added to replace DER_MISMATCH
- Libcart rolled to 3.2.0-1
Singed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

CART-89 err: New DER_GRPVER error code added

---

src/cart/_structures_from_macros_.h
src/cart/crt_context.c
src/cart/crt_group.c
src/cart/crt_rpc.c
src/cart/crt_swim.c
src/cart/crt_swim.h
src/include/cart/swim.h
src/swim/swim.c
src/test/test_corpc_exclusive.c
src/test/test_corpc_prefwd.c
src/test/test_swim.c
src/test/test_swim_net.c

During bootstrapping not all members initialized in the same time.
So, to avoid false positive DEAD detection during bootstrapping
let's introduce INACTIVE status for member which mean the following:
- member will be INACTIVE until first ping response or remove
- each member will try to ping it but just ignore if it fails

CART-730 swim: introduce INACTIVE member status

---

src/cart/crt_corpc.c
src/cart/crt_hg.c
src/test/SConscript
src/test/no_pmix_corpc_errors.c
test/corpc/cart_corpc_one_node.yaml

- When corpc handler is called on the root node, previously a return
from the handler with error triggered failure in the whole corpc
and completion cb execution. Instead we now wait for all children
to respond first before cb is executed.

CART-811 corpc: Fix early corpc return on error

---

src/include/gurt/errno.h

Just to add 3 DAOS err code DER_DF_INVAL/DER_DF_INCOMPT/DER_REC_SIZE.

DAOS-3600 gurt: add errno of DER_DF_INVAL/DER_DF_INCOMPT/DER_REC_SIZE

---

src/cart/crt_group.c
src/cart/crt_group.h
src/include/cart/types.h

CART-89 type: Move CRT_NO_RANK to external header file

---

SConstruct

Use env_modules.py in new location
This can later be installed to reduce code in crt_utils.py
and to make it more robust.   But for now, just putting
it in new location so daos can use it for tests.

CART-89 build: Update to latest scons_local

---

utils/rpms/cart.spec

Updates scons_local to get an env_modules fix with python3
Removes dependence on openmpi-devel from cart rpm spec

CART-89 build: Fix some build issues with orterun removal

---

src/cart/crt_group.c
src/test/tests_common.h
test/util/cart_utils.py

- Each tests binary now logs into its own cart.log[pid] file
- DBG_PRINT echoes also into cart log
- reduced paths in log dirs to increase readability.

CART-89 logs: Test log changes

---

SConstruct
src/cart/crt_barrier.c
src/cart/crt_corpc.c
src/cart/crt_group.c
src/cart/crt_group.h
src/cart/crt_init.c
src/cart/crt_tree.c
test/group_test/group_test.yaml

- Secondary groups are now stored in linked list inside of primary
group.
- Group test was missing entry making one of tests not run

CART-805 groups: Remove restriction on number of secondary groups

---

src/cart/crt_group.c

When uri is inserted today, it creates a corresponding entry
in hg_addr cache. Previously code in cart would insert uri only
for a context on which call was performed, leaving hg_addr entries
for other contexts not created.
This creates a problem due to current mechanic of lc_lookup() internal
call which goes through hg_addr cache first in order to then access
uri cache.
As such if for example uri was added on ctx=2, and later looked up
on ctx=0, the ctx=0 lookup might fail due to not having associated
hg_addr tracking entry (which points to uri cache).
This current workaround makes uri's being inserted into all contexts
thus creating hg_addr tracking entries for every one fo them

CART-89 cache: Cache workaround

---

README.env
SConstruct
src/cart/crt_hg.c
src/cart/crt_init.c
utils/rpms/cart.spec
utils/rpms/debian/changelog

- Legacy ofi+verbs support is now removed; instead ofi+verbs;ofi_rxm
should be used. Appropriate error message added

CART-89 verbs: Remove legacy ofi+verbs support/mention

---

SConstruct
src/crt_launch/SConscript

This enables user to set PKG_CONFIG_PATH and use the
pkg-config name to load MPI rather than relying on
cart to find openmpi.   This is primarily to give
developers finer control

CART-89 build: Add MPI_PKG option for finer control

---

src/crt_launch/SConscript

This enables using mpicc to build MPI applications from external
path in case a package configuration file doesn't exist

CART-89 build: Use mpicc if it's in the path and MPI_PKG is set

---

src/self_test/self_test.c
test/selftest/cart_selftest_three_node.py
test/selftest/cart_selftest_three_node.yaml

master-endpoint must be specified for selftest to work correctly

CART-833 Make master-endpoint arg mandatory in selftest

---

src/cart/crt_hg_proc.c

In DAOS usage it is possible with optional string in RPC, should not add
a err log for that. And remove a few useless logs.

DAOS-3600 gurt: fix error in crt_proc_d_string_t

---

src/crt_launch/SConscript

Otherwise, it can pick up an mpicc in the standard path

CART-89 build: Prepend rather than Append mpi path

---

utils/rpms/cart.spec

Until we can get a stable upstreadm release of mercury which will
properly  create Requires: automatically that reflect the shared library
verison, pin the exact version of mercury we need.

DAOS-3991 install: Requires: mercury with version

---

src/cart/crt_corpc.c

Fix refcount issue on corpcs during handlign of error condition

DAOS-4012 corpc: refcount issue

---

src/cart/crt_corpc.c

Children rpcs were not set to use the same tag as original corpc request

CART-89 fix: Fix corpc tag

---

LICENSE
README.env
src/cart/_structures_from_macros_.h
src/gurt/dlog.c
src/include/gurt/debug.h
utils/rpms/cart.spec
utils/rpms/debian/changelog

- Added new D_LOG_TRUNCATE environment variable to set log file size
to 0 when set.

CART-89 log: D_LOG_TRUNCATE env added

---

utils/build.config
utils/rpms/cart.spec

Disable/remove mercury patch for now as it is causing segfaults
when running multiple servers with verbs

CART-89 mercury: Disable mercury patch

---

src/cart/crt_iv.c
src/include/cart/api.h
src/test/no_pmix_corpc_errors.c

Move req send cb to separate ULT for DAOS, otherwise
it may block crt_progress so it can not process any
request, then being evicted.

CART-851 crt_iv: move req send cb to separate ULT

---

src/cart/crt_iv.c

In call_pre_sync_cb, it should use tmp_iv, which
is gotten from bulk access, instead of iv_value.

CART-863 cart: typo in call_pre_sync_cb

---

src/include/gurt/debug.h

CART-843 gurt: add timestamp to D_PRINT

---

utils/rpms/cart.spec

So move it to cart-tests so that the main package does not require
openmpi.
Skip-test: true

DAOS-4276 build: crt_launch is a test tool

---

src/gurt/dlog.c

Change daos log file mode to 0600.

CART-873 dlog: change log format to 0600

---

src/include/gurt/debug.h

Revert PR-347, since timestamp in D_PRINT mess up
dmg console output.

CART-843 gurt: Remove timestamp from D_PRINT

---

utils/rpms/cart.spec

Remove util/{docker,rpms} from the RPM.
Move /usr/etc/ to /etc/.

DAOS-4412 build: Clean up RPM content

---

utils/rpms/cart.spec

DAOS-4481 build: Remove openmpi3-devel from

---

src/cart/crt_init.c
src/gurt/fault_inject.c
src/include/gurt/fault_inject.h

remove id0 memory check, i.e. it is not
necessary for normal yml.
Add fault injection yml for daos failure.
Remove global d_fault_inject check in data_init(), which
might be messed up if crt_opt is not being set.
master-PR:2335
Signed-off-by: Di Wang di.wang@intel.com

DAOS-4418 fail:Some fixes for fault injection yml

---

src/cart/crt_init.c

- Setting FI_UNIVERSE_SIZE to 2048 if it is not set already in the
environment.
- Added dumping of that envariable at startup as well.

CART-871 env: Setting FI_UNIVERSE_SIZE to 2048 if not set

---

README.env
src/cart/crt_init.c
utils/rpms/cart.spec

- Due to issues in MR caching, a workaround to pin memory on the
server side in order to avoid buffer corruptions during
the situation when multiple clients rdma close to each other.

CART-890 mem: Enable memory pinning workaround for MR cache

---

test/util/cart_utils.py

- Pass --mca pml ob1 for all providers to fix ucx issue instead of
only doing it for psm2

DAOS-4689 ucx: Fix ucx error during runtime

---

src/cart/crt_init.c

For RXM-based providers (verbs, tcp), set FI_OFI_RXM_USE_SRX to
1 if the envariable is not set.
This prevents memory consumption on server side from growing for
each additional client reconnect, allowing to scale up

DAOS-4238 srx: Enable shared receive buffers for rxm providers

---

src/cart/crt_corpc.c
src/cart/crt_group.c
src/cart/crt_group.h
src/cart/crt_iv.c
src/cart/crt_tree.c

Secondary groups were being previously intialized incorrectly with
gp_self field set to 0 instead of CRT_NO_RANK.
additional checks added to fail early if group is detected as
not being fully initialized (having CRT_NO_RANK for gp_self)

DAOS-4423 grp: Fix setting of gp_self for secondary groups

---

SConstruct
utils/rpms/cart.spec

- Update cart to version 4.7.0 as the minor bump was missed
during new fi function addition

CART-89 build: Update cart version to 4.7.0

---

utils/build.config
utils/rpms/cart.spec

- Update to latest OFI in order to pick sockets provider patch
- Apply additional custom sockets provider patch to fix SOAK failures

DAOS-4394 ofi: Update to latest OFI and apply sockets provider patch

---

SConstruct
src/cart/crt_init.c
src/cart/crt_rpc.c
src/gurt/fault_inject.c
src/include/gurt/fault_inject.h
src/test/SConscript
src/test/fault_status.c
utils/rpms/cart.spec

The fault injection framework in CART is a developer/test focused feature. The
feature should not be present in production systems so it is not built in by
default. It can be enabled by specifying --with-fault-injection on the scons
build line.
Signed-off-by: David Quigley <david.quigley@intel.com>

DAOS-723 Fault: Allow Fault Injection framework to be compiled out
