src/cart/crt_register.c, src/include/gurt/common.h, src/include/gurt/types.h, src/test/iv_client.c
Change-Id: If620d76678bf4f6481c944670e63b6b9be4000b3
=> CART-557 gurt: add address validation

utils/build.config
Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>
=> Update Mercury and OFI to latest releases.

src/cart/crt_swim.c, src/swim/swim.c
Fix the case where member was removed but it still is used for ping
or update process. Also updated debug messages in common form.
=> CART-594 swim: few fixes for SWIM in case of remove rank

src/cart/SConscript, src/include/gurt/atomic.h
=> CART-89 fix: Fix build issue

src/cart/crt_context.c
revert the previous fix double cancel patch. It's not the right
solution.
=> CART-89 timeout: revert pr-115

Jenkinsfile, Makefile, cart.spec, multi-node-test.sh, utils/docker/Dockerfile-mockbuild.centos:7, utils/docker/Dockerfile.centos:7
Also:
- notify GitHub commit status when staritng and when done.
- have devel depend on the main package since we only have the
unversioned library at the moement which is in the main package
=> Split out -devel package

Jenkinsfile, utils/docker/Dockerfile-mockbuild.centos:7
Have to remember to put things that can fail but not terminate
the job in if ; then fi blocks.
=> CORCI-89 Use proper shell error handling

Jenkinsfile, utils/docker/Dockerfile.leap.42.3, utils/docker/Dockerfile.sles.12.3
Signed-off-by: John.E.Malmberg <john.e.malmberg@intel.com>
=> CORCI-638 Add sles12.3 and leap42.3 builds

Jenkinsfile, SConstruct, utils/build-master.config
Enable CaRT build with OFI,Mercury,OpenPA master branch in CI
=> CART-618 Enable CaRT build with OFI,Mercury,OpenPA master branch

src/cart/crt_context.c, src/cart/crt_init.c, src/cart/crt_internal_types.h
=> CART-693 progress: avoid lock and list traverse overhead when possible

NOTICE
=> CART-89 fix: Fix date in NOTICE file Fix copyright date in the file

utils/build.config
=> CART-89 ofi: Update to latest libfabric

SConstruct, cart.spec
=> Bump version to 1.0.0

src/cart/crt_rpc.c, src/test/test_group.c, test/corpc/cart_corpc_five_node.yaml, test/corpc/cart_corpc_one_node.yaml, test/corpc/cart_corpc_two_node.yaml
=> - Fixed issue where PMIX mode did not contact psr properly - Fixed issue with PMIX lookup not using primary rank in some cases

src/cart/crt_rpc.c, src/cart/crt_tree.c
Recent merges caused build failures.
=> CART-89 build: Fix broken build

src/cart/crt_iv.c
For some operations CORPC cci_rc was being ignored previously
=> CART-774 iv: iv operation cci_rc fix

Jenkinsfile, test/SConscript, utils/docker/Dockerfile-debbuild.ubuntu.18.04, utils/docker/Dockerfile.centos.7
Moves build to python3
Updates scons_local to get python3 support
=> DAOS-3268 build: Update CentOS build to python3

src/self_test/SConscript, src/self_test/self_test.c, test/selftest/cart_selftest_two_node.yaml
Enable CaRT selftest to run with no pmix
=> CART-725 No PMIX Test Conversion (selftest)

Jenkinsfile
=> CART-89 build: Build on landing to daos_devel1

src/cart/crt_iv.c
=> CART-802 iv: Phase1 of going over ivns references

src/cart/crt_group.c
=> CART-89 fix: off by 1 error in address string

src/test/test_no_timeout.c, test/rpc/cart_rpc_one_node.yaml, test/rpc/cart_rpc_two_node.yaml
Converting the no_timeout test to no pmix
=> CART-815 No PMIX Test Conversion - RPC no_timeout

utils/rpms/cart.spec, utils/rpms/debian/changelog, utils/rpms/debian/control
Restrict mercury version to be < 1.0.1-21
=> CART-89 build: Restrict mercury

src/ctl/cart_ctl.c, src/test/test_crt_barrier.c, src/test/test_ep_cred_client.c, src/test/test_ep_cred_common.h, src/test/test_ep_cred_server.c, src/test/test_group_np_cli.c, src/test/test_group_np_common.h, src/test/test_group_np_srv.c, src/test/test_no_timeout.c, src/test/test_proto_client.c, src/test/test_proto_common.h, src/test/test_proto_server.c, src/test/tests_common.h, test/rpc/cart_rpc_one_node.yaml, test/rpc/cart_rpc_two_node.yaml
Converting ep credits tests to no pmix.
=> CART-814 No PMIX Test Conversion - ep credits

src/include/gurt/common.h
On Linux, realloc(p, 0) may return NULL after freeing p. This behavior
has proved tricky, as it is easy to mistake the NULL return value for an
error and keep using the dangling p. We therefore allocate a 1-byte
object in this case, simulating the BSD behavior.
Signed-off-by: Li Wei <wei.g.li@intel.com>
=> CART-823 gurt: Fix D_REALLOC_COMMON for 0 sizes

src/gurt/debug.c
=> CART-89 build: Fix ignored asprintf return

src/gurt/dlog.c
A bug in logging was exposed when someone uses a log facility
before logging is initialized.   The initialization code resets
the cached entries when it synchronizes against the envirable
settings.   However, it was only doing this reset if D_LOG_MASK
included a specific facility.  This moves the reset so it's outside
of the body of the loop which is more efficient anyway.
=> CART-89 log: Move reset_cache code for logging

src/cart/crt_group.c, src/cart/crt_swim.c, src/cart/crt_swim.h
- change lock type (use simple SPIN lock)
- change locks order (avoid inner locks)
- add check for client or server for few APIs
=> CART-808 swim: simplify lock usage

SConstruct, src/cart/crt_barrier.c, src/cart/crt_corpc.c, src/cart/crt_group.c, src/cart/crt_group.h, src/cart/crt_iv.c, src/cart/crt_rpc.h, src/cart/crt_tree.c, src/include/cart/api.h, src/include/cart/types.h, src/test/crt_echo_srv.c, utils/rpms/cart.spec, utils/rpms/debian/changelog
- Further cleanup after PMIX removal
=> CART-89 cleanup: Cleanup groups

src/cart/crt_init.c
=> CART-89 log: dump envariables into log file at startup

Jenkinsfile
=> CART-89 build: Add per test stage Skip pragmas

SConstruct, src/crt_launch/SConscript, utils/build.config
Update scons_local again to get newer version of components
Add copyright updates
=> CART-89 build: A little cleanup from last patch

src/cart/crt_iv.c
- sg_iovs prior to crt_bulk_access are allocated based on
iv_value's sg_nr.
- iv_value is now retrieved via on_get() using READ permission
since iv_value's contents are not being modified
=> CART-835 iv: Fix issue with bulk access

SConstruct, src/cart/crt_iv.c, src/include/cart/iv.h, utils/rpms/cart.spec, utils/rpms/debian/changelog
- New IV APIs added: crt_iv_namespace_priv_set/get
- Version rolled to 4.4.0-1
=> CART-839 iv: associate private user data with iv namespace

test/barrier/cart_barrier_five_node.yaml, test/ctl/cart_ctl_five_node.py, test/ctl/cart_ctl_one_node.py, test/group_tiers/cart_group_tiers_three_node.py, test/rpc/cart_rpc_one_node.py, test/rpc/cart_rpc_two_node.py, test/selftest/cart_selftest_three_node.py, test/util/cart_utils.py, utils/memcheck-cart.supp
- --mca pml ob1  option added to orterun to avoid bug in case of psm2
- OFI_DOMAIN is now parsed from yaml files if it is specified
=> CART-89 test: Fixes to tests

utils/build.config, utils/memcheck-cart.supp
Update to latest libfabric (3db1d7b184ee99eee6532b76eadffb1b722e353e)
=> CART-89 ofi: update ot latest libfabric

utils/build.config
Fix ofi build by updating to 955f3a07dd011fb1dbfa6b6c772ada03d5af320e
=> CART-89 ofi: Fix ofi build

utils/build.config, utils/rpms/cart.spec
update mercury to latest commit in master
=> CART-89 build: update mercury

src/cart/crt_swim.c, src/test/iv_common.h, src/test/iv_server.c
- Incorrect ranks were being used by crt_swim_init()
=> CART-849 swim: Incorrect ranks used by crt_swim_init()

Jenkinsfile, src/utest/test_linkage.cpp, utils/build.config, utils/rpms/packaging/Dockerfile.mockbuild
=> CART-89 build: Update to latest packaging

utils/build.config
=> CART-89 ofi: Update to master tip

src/test/test_corpc_prefwd.c, test/corpc/cart_corpc_one_node.yaml, test/group_test/group_test.yaml, utils/build.config, utils/rpms/cart.spec
Update mercury to ad5a3b3dbf171a97e1ca5f1683299db1c69b03ea
=> CART-89 mercury: Update mercury

utils/docker/Dockerfile.leap.15
Fixup Dockerfile.leap.15 to make sure it has the mozilla certificate package.
Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>
=> CORCI-833 Build: Fixup OpenSuse 15 dockerfile

utils/build.config, utils/rpms/cart.spec
=> CART-89 updates: Update OFI and mercury to latest

README.env, src/cart/crt_hg.c, src/cart/crt_hg.h, src/cart/crt_init.c
- Enable "ofi+tcp;ofi_rxm" provider
=> CART-89 tcp: Enable tcp provider

utils/build.config, utils/rpms/cart.spec
=> CART-89 ofi: update to 62f6c937601776dac8a1f97c8bb1b1a6acfbc3c0

utils/build.config, utils/rpms/cart.spec
Update to mercury 4871023058887444d47ead4d089c99db979f3d93 to get
fix for a race condition in na_ofi.c
=> CART-89 mercury: Update mercury to 4871023058887444d47ead4d089c99db979f3d93

SConstruct, utils/rpms/cart.spec
=> CART-89 build: Update version to 4.6.1
